name: CI
on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: |
          if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
          export PATH="~/@tstahn/neo/node_modules/.bin:$PATH"
          npm ci
      - name: Compile Sass
        run: ./node_modules/.bin/sass example.main.scss test/example.main.css --no-source-map
      - name: Run test
        run: npm test
      - name: Status
        run: |
          git status
          git status | grep -q "nothing to commit, working tree clean"
