name: CI
on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Compile
        run: ./node_modules/.bin/sass example.main.scss test/example.main.css --no-source-map
      - name: Test
        run: npm test
      - name: Status
        run: |
          git status
          git status | grep -q "nothing to commit, working tree clean"
